### ISSUE TITLE
Disable when project doesn't use XO

### ISSUE THREAD

**Issue by wmertens** [SamVerschueren/vscode-linter-xo#14] opened 2016-07-17 21:08 UTC
Similar to https://github.com/sindresorhus/atom-linter-xo/blob/master/index.js#L28-L34

**Comment by SamVerschueren** [comment] 2016-07-17 21:11
Duplicate of #8 :)

**Closed by SamVerschueren** 2016-07-17 21:11 UTC

**Comment by wmertens** [comment] 2016-07-17 21:12
D'oh! Sorry :)
