### ISSUE TITLE
Failed to load config "xo/esnext" to extend from. Referenced from: BaseConfig

### ISSUE THREAD

**Issue by hanakin** [SamVerschueren/vscode-linter-xo#92] opened 2021-05-16 23:48 UTC
after installing the ext and loading up a js file I get the above error in vscode

here is my config

```
"xo": {
		"rules": {
			"quotes": [
				"error",
				"single"
			],
			"comma-dangle": [
				"error",
				"always-multiline"
			],
			"block-spacing": "error",
			"array-bracket-spacing": [
				"error",
				"always"
			],
			"multiline-comment-style": "off",
			"computed-property-spacing": "off",
			"space-in-parens": "off",
			"capitalized-comments": "off",
			"object-curly-spacing": [
				"error",
				"always"
			],
			"no-lonely-if": "off"
		},
		"env": [
			"es6",
			"browser",
			"node",
			"jquery"
		]
	},
```

**Comment by yakov116** [comment] 2021-08-03 14:52
Duplicate of #91

**Closed** 2021-08-03 14:54 UTC
